apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/jtteotn9/tea-bot
  newName: ghcr.io/jtteotn9/tea-bot
  newTag: sha-9f39027

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
        - secretRef:
            name: tea-bot-env
  target:
    kind: Deployment
    name: tea-bot
